import { User, Task, KPI, KPIResult, Integration } from './types';

export const SEED_USERS: User[] = [
  {
    id: 'user-admin',
    name: 'Sarah Jenkins',
    email: 'admin@teampulse.com',
    role: 'admin',
    managerId: null,
    department: 'Executive Engineering',
    title: 'VP of Engineering & Systems',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    joinedDate: '2022-03-15',
    phone: '+1 (555) 019-2834',
    location: 'San Francisco, CA',
  },
  {
    id: 'user-ahmed',
    name: 'Ahmed Khan',
    email: 'ahmed@teampulse.com',
    role: 'manager',
    managerId: 'user-admin',
    department: 'Core Platform Engineering',
    title: 'Engineering Manager',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    joinedDate: '2023-01-10',
    phone: '+1 (555) 018-7744',
    location: 'Seattle, WA',
  },
  // Ahmed's 7 Direct Reports
  {
    id: 'user-harsh',
    name: 'Harsh Patel',
    email: 'harsh@teampulse.com',
    role: 'employee',
    managerId: 'user-ahmed',
    department: 'Core Platform Engineering',
    title: 'Senior Frontend Engineer',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    joinedDate: '2023-04-12',
    phone: '+1 (555) 017-9102',
    location: 'Austin, TX',
  },
  {
    id: 'user-advita',
    name: 'Advita Sharma',
    email: 'advita@teampulse.com',
    role: 'employee',
    managerId: 'user-ahmed',
    department: 'Core Platform Engineering',
    title: 'Full Stack Engineer',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    joinedDate: '2023-06-01',
    phone: '+1 (555) 017-8823',
    location: 'San Jose, CA',
  },
  {
    id: 'user-vaibhav',
    name: 'Vaibhav Pansare',
    email: 'vaibhav@teampulse.com',
    role: 'employee',
    managerId: 'user-ahmed',
    department: 'Core Platform Engineering',
    title: 'Backend & Distributed Systems Engineer',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    joinedDate: '2023-02-18',
    phone: '+1 (555) 017-4390',
    location: 'New York, NY',
  },
  {
    id: 'user-akash',
    name: 'Akash Verma',
    email: 'akash@teampulse.com',
    role: 'employee',
    managerId: 'user-ahmed',
    department: 'Core Platform Engineering',
    title: 'QA & Test Automation Specialist',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    joinedDate: '2023-08-15',
    phone: '+1 (555) 017-5511',
    location: 'Chicago, IL',
  },
  {
    id: 'user-om',
    name: 'Om Gupta',
    email: 'om@teampulse.com',
    role: 'employee',
    managerId: 'user-ahmed',
    department: 'Core Platform Engineering',
    title: 'DevOps & Cloud SRE Architect',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    joinedDate: '2023-05-20',
    phone: '+1 (555) 017-1099',
    location: 'Boston, MA',
  },
  {
    id: 'user-mayank',
    name: 'Mayank Joshi',
    email: 'mayank@teampulse.com',
    role: 'employee',
    managerId: 'user-ahmed',
    department: 'Core Platform Engineering',
    title: 'UI/UX & Design Systems Engineer',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    joinedDate: '2023-09-01',
    phone: '+1 (555) 017-6421',
    location: 'Denver, CO',
  },
  {
    id: 'user-yaddhnesh',
    name: 'Yaddhnesh Rane',
    email: 'yaddhnesh@teampulse.com',
    role: 'employee',
    managerId: 'user-ahmed',
    department: 'Core Platform Engineering',
    title: 'Mobile & API Systems Engineer',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    joinedDate: '2023-07-11',
    phone: '+1 (555) 017-3199',
    location: 'Atlanta, GA',
  },
  // Secondary manager for rich team comparison
  {
    id: 'user-elena',
    name: 'Elena Rostova',
    email: 'elena@teampulse.com',
    role: 'manager',
    managerId: 'user-admin',
    department: 'Data & Analytics',
    title: 'Data Platform Manager',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    joinedDate: '2022-11-10',
    phone: '+1 (555) 018-9901',
    location: 'San Francisco, CA',
  },
  {
    id: 'user-carlos',
    name: 'Carlos Gomez',
    email: 'carlos@teampulse.com',
    role: 'employee',
    managerId: 'user-elena',
    department: 'Data & Analytics',
    title: 'Data Pipeline Engineer',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    joinedDate: '2023-03-01',
    phone: '+1 (555) 017-2244',
    location: 'Austin, TX',
  },
  {
    id: 'user-priya',
    name: 'Priya Nair',
    email: 'priya@teampulse.com',
    role: 'employee',
    managerId: 'user-elena',
    department: 'Data & Analytics',
    title: 'Machine Learning Analyst',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    joinedDate: '2023-07-22',
    phone: '+1 (555) 017-7788',
    location: 'San Jose, CA',
  },
];

export const SEED_KPIS: KPI[] = [
  {
    id: 'kpi-1',
    name: 'Task Completion Rate',
    description: 'Percentage of assigned tasks completed during the evaluation period.',
    ownerManagerId: 'user-ahmed',
    appliesToUserIds: 'ALL',
    metricType: 'percentage',
    direction: 'higher_is_better',
    targetValue: 88,
    weight: 20,
    frequency: 'monthly',
    unit: '%',
    isSystemCalculated: true,
    systemCalculationType: 'task_completion_rate',
  },
  {
    id: 'kpi-2',
    name: 'On-Time Delivery Rate',
    description: 'Percentage of tasks completed on or before the specified due date.',
    ownerManagerId: 'user-ahmed',
    appliesToUserIds: 'ALL',
    metricType: 'percentage',
    direction: 'higher_is_better',
    targetValue: 90,
    weight: 20,
    frequency: 'monthly',
    unit: '%',
    isSystemCalculated: true,
    systemCalculationType: 'on_time_delivery',
  },
  {
    id: 'kpi-3',
    name: 'Average Cycle Time',
    description: 'Average days elapsed from task start to completion.',
    ownerManagerId: 'user-ahmed',
    appliesToUserIds: 'ALL',
    metricType: 'numeric',
    direction: 'lower_is_better',
    targetValue: 3.5,
    weight: 15,
    frequency: 'weekly',
    unit: 'days',
    isSystemCalculated: true,
    systemCalculationType: 'cycle_time',
  },
  {
    id: 'kpi-4',
    name: 'Rally Story Points Delivered',
    description: 'Total velocity points closed across synchronized Agile sprints.',
    ownerManagerId: 'user-ahmed',
    appliesToUserIds: 'ALL',
    metricType: 'numeric',
    direction: 'higher_is_better',
    targetValue: 24,
    weight: 15,
    frequency: 'monthly',
    unit: 'pts',
    isSystemCalculated: true,
    systemCalculationType: 'rally_story_points',
  },
  {
    id: 'kpi-5',
    name: 'Workday Utilization & Compliance',
    description: 'Timesheet logging accuracy and mandatory compliance module completion.',
    ownerManagerId: 'user-ahmed',
    appliesToUserIds: 'ALL',
    metricType: 'percentage',
    direction: 'higher_is_better',
    targetValue: 95,
    weight: 15,
    frequency: 'monthly',
    unit: '%',
    isSystemCalculated: true,
    systemCalculationType: 'workday_utilization',
  },
  {
    id: 'kpi-6',
    name: 'Manager Technical Excellence Rating',
    description: 'Quarterly code review quality, architectural rigor, and mentorship review by direct manager.',
    ownerManagerId: 'user-ahmed',
    appliesToUserIds: 'ALL',
    metricType: 'rating_scale',
    direction: 'higher_is_better',
    targetValue: 4.5,
    weight: 15,
    frequency: 'quarterly',
    unit: '/5.0',
    isSystemCalculated: false,
    systemCalculationType: 'manager_rating',
  },
];

export const SEED_TASKS: Task[] = [
  // Harsh Patel tasks
  {
    id: 'task-101',
    assignedTo: 'user-harsh',
    createdBy: 'user-ahmed',
    title: 'Migrate React Components to Tailwind CSS Design Tokens',
    description: 'Refactor legacy styled components to atomic utility classes and ensure dark mode accessibility.',
    category: 'Design System',
    startDate: '2026-08-01',
    dueDate: '2026-08-10',
    completedDate: '2026-08-09',
    status: 'completed',
    priority: 'high',
    estimatedHours: 24,
    actualHours: 22,
    source: 'manual',
    approved: true,
  },
  {
    id: 'task-102',
    assignedTo: 'user-harsh',
    createdBy: 'user-harsh',
    title: 'Optimize Virtualized Table Rendering for 10k Records',
    description: 'Implement windowing and canvas optimizations to sustain 60fps scrolling.',
    category: 'Frontend Performance',
    startDate: '2026-08-12',
    dueDate: '2026-08-20',
    completedDate: '2026-08-19',
    status: 'completed',
    priority: 'urgent',
    estimatedHours: 28,
    actualHours: 26,
    source: 'manual',
    approved: true,
  },
  {
    id: 'task-103',
    assignedTo: 'user-harsh',
    createdBy: 'user-ahmed',
    title: 'Rally: US-3901 Implement Accessible Combobox & Filter Pill Controls',
    description: 'ARIA 1.2 compliant combobox with keyboard navigation and screen reader announcements.',
    category: 'Rally Sprint 44',
    startDate: '2026-08-15',
    dueDate: '2026-08-26',
    status: 'in_progress',
    priority: 'medium',
    estimatedHours: 18,
    actualHours: 12,
    source: 'rally',
    storyPoints: 5,
    approved: true,
  },
  // Advita Sharma tasks
  {
    id: 'task-104',
    assignedTo: 'user-advita',
    createdBy: 'user-ahmed',
    title: 'Build GraphQL Federation Subgraph for User Roles',
    description: 'Expose RBAC authorization directives and unify schema across microservices.',
    category: 'API Architecture',
    startDate: '2026-08-02',
    dueDate: '2026-08-12',
    completedDate: '2026-08-11',
    status: 'completed',
    priority: 'high',
    estimatedHours: 32,
    actualHours: 30,
    source: 'manual',
    approved: true,
  },
  {
    id: 'task-105',
    assignedTo: 'user-advita',
    createdBy: 'user-advita',
    title: 'Rally: US-4011 Webhook Ingestion & Dead Letter Queue Handler',
    description: 'Resilient event processing with exponential backoff and Cloud Pub/Sub subscriptions.',
    category: 'Event Systems',
    startDate: '2026-08-14',
    dueDate: '2026-08-24',
    completedDate: '2026-08-23',
    status: 'completed',
    priority: 'urgent',
    estimatedHours: 25,
    actualHours: 24,
    source: 'rally',
    storyPoints: 8,
    approved: true,
  },
  {
    id: 'task-106',
    assignedTo: 'user-advita',
    createdBy: 'user-ahmed',
    title: 'Workday: WD-COMP-101 Mandatory SOC2 Security Attestation',
    description: 'Complete credential rotation audit and security policy compliance verification.',
    category: 'Compliance',
    startDate: '2026-08-10',
    dueDate: '2026-08-15',
    completedDate: '2026-08-14',
    status: 'completed',
    priority: 'medium',
    estimatedHours: 4,
    actualHours: 4,
    source: 'workday',
    approved: true,
  },
  // Vaibhav Pansare tasks
  {
    id: 'task-107',
    assignedTo: 'user-vaibhav',
    createdBy: 'user-ahmed',
    title: 'Design Multi-Tenant Sharding Strategy for PostgreSQL',
    description: 'Define row-level security and schema-per-tenant connection pooling with PgBouncer.',
    category: 'Database Systems',
    startDate: '2026-08-01',
    dueDate: '2026-08-14',
    completedDate: '2026-08-12',
    status: 'completed',
    priority: 'urgent',
    estimatedHours: 36,
    actualHours: 34,
    source: 'manual',
    approved: true,
  },
  {
    id: 'task-108',
    assignedTo: 'user-vaibhav',
    createdBy: 'user-vaibhav',
    title: 'Rally: US-4210 Distributed Lock Engine using Redis Redlock',
    description: 'Implement distributed mutual exclusion for concurrent batch calculation jobs.',
    category: 'Core Distributed',
    startDate: '2026-08-10',
    dueDate: '2026-08-21',
    completedDate: '2026-08-19',
    status: 'completed',
    priority: 'high',
    estimatedHours: 20,
    actualHours: 19,
    source: 'rally',
    storyPoints: 8,
    approved: true,
  },
  {
    id: 'task-109',
    assignedTo: 'user-vaibhav',
    createdBy: 'user-ahmed',
    title: 'Benchmark gRPC vs REST Inter-Service Throughput',
    description: 'Generate load test metrics using k6 and analyze latency p99 distributions.',
    category: 'Performance Benchmarking',
    startDate: '2026-08-18',
    dueDate: '2026-08-28',
    status: 'in_progress',
    priority: 'medium',
    estimatedHours: 22,
    actualHours: 14,
    source: 'manual',
    approved: true,
  },
  // Akash Verma tasks
  {
    id: 'task-110',
    assignedTo: 'user-akash',
    createdBy: 'user-ahmed',
    title: 'Author Automated Regression Test Matrix for Core APIs',
    description: '100% coverage on critical authentication, task creation, and scoring algorithms.',
    category: 'QA Engineering',
    startDate: '2026-08-04',
    dueDate: '2026-08-15',
    completedDate: '2026-08-14',
    status: 'completed',
    priority: 'high',
    estimatedHours: 28,
    actualHours: 27,
    source: 'manual',
    approved: true,
  },
  {
    id: 'task-111',
    assignedTo: 'user-akash',
    createdBy: 'user-akash',
    title: 'Rally: DE-1920 Fix Flaky Playwright Visual Regression Snapshots',
    description: 'Stabilize font smoothing and hydration animations in CI headless Chrome runs.',
    category: 'QA Tooling',
    startDate: '2026-08-16',
    dueDate: '2026-08-22',
    completedDate: '2026-08-21',
    status: 'completed',
    priority: 'medium',
    estimatedHours: 16,
    actualHours: 15,
    source: 'rally',
    storyPoints: 5,
    approved: true,
  },
  {
    id: 'task-112',
    assignedTo: 'user-akash',
    createdBy: 'user-ahmed',
    title: 'Setup Automated Accessibility (a11y) Axe Linter in GitHub Actions',
    description: 'Enforce WCAG 2.1 AA compliance gates on all Pull Requests.',
    category: 'CI/CD & a11y',
    startDate: '2026-08-20',
    dueDate: '2026-08-29',
    status: 'in_progress',
    priority: 'low',
    estimatedHours: 14,
    actualHours: 6,
    source: 'manual',
    approved: true,
  },
  // Om Gupta tasks
  {
    id: 'task-113',
    assignedTo: 'user-om',
    createdBy: 'user-ahmed',
    title: 'Zero-Downtime Canary Deployment Pipeline for Kubernetes',
    description: 'Configure Argo Rollouts with automated metric analysis and instant rollback.',
    category: 'DevOps / SRE',
    startDate: '2026-08-03',
    dueDate: '2026-08-13',
    completedDate: '2026-08-12',
    status: 'completed',
    priority: 'urgent',
    estimatedHours: 35,
    actualHours: 32,
    source: 'manual',
    approved: true,
  },
  {
    id: 'task-114',
    assignedTo: 'user-om',
    createdBy: 'user-om',
    title: 'Rally: US-4330 Terraform Infrastructure as Code for Cloud SQL Replica',
    description: 'Automate multi-region failover and read-replica provisioning.',
    category: 'Cloud Infrastructure',
    startDate: '2026-08-12',
    dueDate: '2026-08-22',
    completedDate: '2026-08-21',
    status: 'completed',
    priority: 'high',
    estimatedHours: 24,
    actualHours: 22,
    source: 'rally',
    storyPoints: 8,
    approved: true,
  },
  {
    id: 'task-115',
    assignedTo: 'user-om',
    createdBy: 'user-ahmed',
    title: 'Configure Prometheus & Grafana Distributed Tracing Dashboards',
    description: 'Correlate OpenTelemetry spans with memory leak alerts.',
    category: 'Observability',
    startDate: '2026-08-19',
    dueDate: '2026-08-27',
    status: 'blocked',
    priority: 'high',
    estimatedHours: 20,
    actualHours: 12,
    source: 'manual',
    approved: false,
  },
  // Mayank Joshi tasks
  {
    id: 'task-116',
    assignedTo: 'user-mayank',
    createdBy: 'user-ahmed',
    title: 'Design Component Library Token Hierarchy in Figma & Code',
    description: 'Define semantic color ramps, typographic scale ratios, and elevation maps.',
    category: 'Design Systems',
    startDate: '2026-08-02',
    dueDate: '2026-08-11',
    completedDate: '2026-08-10',
    status: 'completed',
    priority: 'high',
    estimatedHours: 26,
    actualHours: 24,
    source: 'manual',
    approved: true,
  },
  {
    id: 'task-117',
    assignedTo: 'user-mayank',
    createdBy: 'user-mayank',
    title: 'Rally: US-4115 Interactive Radar & Donut Chart Visualizations',
    description: 'Implement animated Recharts components with accessible tooltips and screen-reader tables.',
    category: 'Data Visualization',
    startDate: '2026-08-12',
    dueDate: '2026-08-23',
    completedDate: '2026-08-22',
    status: 'completed',
    priority: 'urgent',
    estimatedHours: 22,
    actualHours: 20,
    source: 'rally',
    storyPoints: 5,
    approved: true,
  },
  {
    id: 'task-118',
    assignedTo: 'user-mayank',
    createdBy: 'user-ahmed',
    title: 'Mobile Touch Target & Responsive Layout Audit',
    description: 'Ensure 44px minimum touch targets and zero horizontal scroll on tablet/mobile.',
    category: 'Mobile UX',
    startDate: '2026-08-18',
    dueDate: '2026-08-28',
    status: 'in_progress',
    priority: 'medium',
    estimatedHours: 16,
    actualHours: 8,
    source: 'manual',
    approved: true,
  },
  // Yaddhnesh Rane tasks
  {
    id: 'task-119',
    assignedTo: 'user-yaddhnesh',
    createdBy: 'user-ahmed',
    title: 'Build Mobile Offline Sync Engine with IndexedDB Cache',
    description: 'Background synchronization worker that queues offline mutations.',
    category: 'Mobile Architecture',
    startDate: '2026-08-01',
    dueDate: '2026-08-12',
    completedDate: '2026-08-11',
    status: 'completed',
    priority: 'urgent',
    estimatedHours: 32,
    actualHours: 30,
    source: 'manual',
    approved: true,
  },
  {
    id: 'task-120',
    assignedTo: 'user-yaddhnesh',
    createdBy: 'user-yaddhnesh',
    title: 'Rally: US-4288 Push Notification Dispatch Service',
    description: 'FCM / APNs notification dispatch pipeline with user preference filters.',
    category: 'Mobile Backend',
    startDate: '2026-08-13',
    dueDate: '2026-08-23',
    completedDate: '2026-08-22',
    status: 'completed',
    priority: 'high',
    estimatedHours: 24,
    actualHours: 22,
    source: 'rally',
    storyPoints: 8,
    approved: true,
  },
  {
    id: 'task-121',
    assignedTo: 'user-yaddhnesh',
    createdBy: 'user-ahmed',
    title: 'Workday: WD-UTIL-204 Professional Cloud Certification Renewal',
    description: 'Upload certification credentials and verify continuing education credits.',
    category: 'HCM Upskilling',
    startDate: '2026-08-16',
    dueDate: '2026-08-25',
    completedDate: '2026-08-24',
    status: 'completed',
    priority: 'low',
    estimatedHours: 6,
    actualHours: 6,
    source: 'workday',
    approved: true,
  },
  // Additional tasks for Elena's team for comparison
  {
    id: 'task-122',
    assignedTo: 'user-carlos',
    createdBy: 'user-elena',
    title: 'Spark Streaming ETL Pipeline for Event Ingestion',
    description: 'Aggregate clickstream telemetry into BigQuery lakehouse partitions.',
    category: 'Data Engineering',
    startDate: '2026-08-05',
    dueDate: '2026-08-18',
    completedDate: '2026-08-17',
    status: 'completed',
    priority: 'high',
    estimatedHours: 30,
    actualHours: 29,
    source: 'manual',
    approved: true,
  },
  {
    id: 'task-123',
    assignedTo: 'user-priya',
    createdBy: 'user-elena',
    title: 'Model Drift Detection and Automated Retraining Workflow',
    description: 'Deploy statistical drift alerts and feature store validation checks.',
    category: 'MLOps',
    startDate: '2026-08-06',
    dueDate: '2026-08-19',
    completedDate: '2026-08-18',
    status: 'completed',
    priority: 'urgent',
    estimatedHours: 32,
    actualHours: 31,
    source: 'manual',
    approved: true,
  },
];

export const SEED_KPI_RESULTS: KPIResult[] = [
  // Manager ratings (Quarterly)
  { id: 'res-1', kpiId: 'kpi-6', userId: 'user-harsh', period: 'Q3 2026', actualValue: 4.8, computedScore: 96, notes: 'Exceptional frontend craftsmanship and prompt mentoring of junior colleagues.', updatedDate: '2026-08-20', evaluatorId: 'user-ahmed' },
  { id: 'res-2', kpiId: 'kpi-6', userId: 'user-advita', period: 'Q3 2026', actualValue: 4.7, computedScore: 94, notes: 'Outstanding cross-stack execution on API federation and pub/sub handlers.', updatedDate: '2026-08-20', evaluatorId: 'user-ahmed' },
  { id: 'res-3', kpiId: 'kpi-6', userId: 'user-vaibhav', period: 'Q3 2026', actualValue: 4.9, computedScore: 98, notes: 'Deep architectural mastery on PostgreSQL sharding and distributed locks.', updatedDate: '2026-08-20', evaluatorId: 'user-ahmed' },
  { id: 'res-4', kpiId: 'kpi-6', userId: 'user-akash', period: 'Q3 2026', actualValue: 4.5, computedScore: 90, notes: 'Significant test coverage gains and robust regression test framework.', updatedDate: '2026-08-20', evaluatorId: 'user-ahmed' },
  { id: 'res-5', kpiId: 'kpi-6', userId: 'user-om', period: 'Q3 2026', actualValue: 4.6, computedScore: 92, notes: 'Superb reliability enhancements with zero-downtime deployment pipelines.', updatedDate: '2026-08-20', evaluatorId: 'user-ahmed' },
  { id: 'res-6', kpiId: 'kpi-6', userId: 'user-mayank', period: 'Q3 2026', actualValue: 4.7, computedScore: 94, notes: 'High visual precision and clean token system implementation.', updatedDate: '2026-08-20', evaluatorId: 'user-ahmed' },
  { id: 'res-7', kpiId: 'kpi-6', userId: 'user-yaddhnesh', period: 'Q3 2026', actualValue: 4.8, computedScore: 96, notes: 'Brilliant offline-first mobile sync architecture and rapid execution.', updatedDate: '2026-08-20', evaluatorId: 'user-ahmed' },
];

export const SEED_INTEGRATIONS: Integration[] = [
  {
    id: 'int-rally',
    type: 'rally',
    name: 'Rally Software (CA Agile Central)',
    connectionStatus: 'connected',
    apiEndpoint: 'https://rally1.rallydev.com/slm/webservice/v2.0',
    authToken: 'rally_sec_tok_9948271827461938a1',
    tenantOrWorkspaceId: 'WS-CORP-ENG-4819',
    syncFrequency: 'daily',
    lastSyncedAt: '2026-08-24T18:30:00.000Z',
    recordsCount: 14,
    autoSync: true,
  },
  {
    id: 'int-workday',
    type: 'workday',
    name: 'Workday Human Capital & Financials (RaaS)',
    connectionStatus: 'connected',
    apiEndpoint: 'https://wd3-impl-services1.workday.com/ccx/service/teampulse/customreport2',
    authToken: 'wd_oauth_client_sec_884910275819304a',
    tenantOrWorkspaceId: 'wd3-teampulse-prod01',
    syncFrequency: 'daily',
    lastSyncedAt: '2026-08-24T19:15:00.000Z',
    recordsCount: 8,
    autoSync: true,
  },
];
